GET  H "Authorization: eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHByb2ZpbGUiLCJleHAiOjE3NjQ5Nzk1NDJ9.XWTaY5hrJ46blx408UOBnPqY7xIhp_oNpG6jd0eKz4FktBwANn14PI_EknrhA8Kc2ybTnmbjvZ6V3FqeGbQb1g"https://www.newtlike.com:3000/api/users/testprofile/history HTTP/1.1
content-type: application/json



